### ISSUE TITLE
[Design] Главное меню

### ISSUE THREAD

**Issue by PoroshinGA** [PavelStalone/GestureTranslator#105]
В :ui /screens создать директорию main и в ней создать класс MainMenuScreen, представляющий собой верстку экрана главного меню. Нужен только экран, без bottomBar и тд

-------------------------------------------------------------------------------

![Image](https://github.com/PavelStalone/GestureTranslator/assets/119220049/ad182023-59aa-474a-a7a6-a556f371930e)

**Comment by kond1ter** [comment]
![Image](https://github.com/PavelStalone/GestureTranslator/assets/61204648/b3133c1b-492d-49a4-93cb-bad388806b84)

Может стоит вынести это уведомление отдальным компонентом
