### ISSUE TITLE
[Design] Диалоговое окно с информацией

### ISSUE THREAD

**Issue by PavelStalone** [PavelStalone/GestureTranslator#111]
Нужно сверстать диалоговое окно, где мы будем писать почему пользователь не может воспользоваться каким-то функционалом.
Например : 

![Image](https://github.com/PavelStalone/GestureTranslator/assets/69467433/5020e5ff-6dad-4210-8219-f2f058134e3b)

Вот ссылка на пример: https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#AlertDialog(kotlin.Function0,androidx.compose.ui.Modifier,androidx.compose.ui.window.DialogProperties,kotlin.Function0) [Нужно немного подождать, сайт долго грузит]

**Comment by PoroshinGA** [comment]
создать в :ui /dialogs
