### ISSUE TITLE
[Design] Окно Регистрации

### ISSUE THREAD

**Issue by PavelStalone** [PavelStalone/GestureTranslator#13]
Создать макет окна регистрации для светлой и темной темы в Figma.

**Comment by N1kySSS** [comment]
Сделал тестовую версию светлой темы

**Comment by PavelStalone** [comment]
Где она находится?

**Comment by N1kySSS** [comment]
наша старая доска на Figma/тесты
слева от макетов

**Comment by PoroshinGA** [comment]
В окне регистрации пользователь заполняет информацию о себе. Оно должно включать в себя следующее:

- Поле ввода никнейма (description - не более 20 символов)
- Поле ввода почты
- Поле ввода пароля
- Поле подтверждения пароля
- Кнопка "Подтвердить"
- Кнопка "Отмена"

**Comment by kond1ter** [comment]
Макет готов для review, он находится в figma на странице Test
