### ISSUE TITLE
[Design] Окно авторизации

### ISSUE THREAD

**Issue by PavelStalone** [PavelStalone/GestureTranslator#14]
Сделать макет окна авторизации в Figma.
Не забыть про возможность восстановить пароль и функции войти без регистрации.

**Comment by PoroshinGA** [comment]
Окно должно содержать:

- Поле ввода логина
- Поле ввода пароля
- Снизу от поля пароля что то вроде кликабельной надписи "Еще нет аккаунта? Зарегистрироваться!"
- В самом низу экрана бледно-серая надпись "Войти без регистрации"

Информацию об ограниченных возможностях в случае входа бещ регистрации на этом жкране писать не нужно! будет просто всплывающее окошко с текстом по типу "Вы можете войти без регистрации, но  таком случае вам могут быть недоступны некоторые функции!" и кнопками "Все равно продолжить" и "Отмена"

**Comment by PoroshinGA** [comment]
Забыл про возможность восстановления пароля. Ее тоже нужно добавить

**Comment by N1kySSS** [comment]
Немного переделали окно авторизации. Можно ли закрывать таск ?
