### ISSUE TITLE
[Design] Нарисовать жесты в векторном формате

### ISSUE THREAD

**Issue by PavelStalone** [PavelStalone/GestureTranslator#20]
Наша задача избавиться от растрового изображения и перейти к векторным.

Можно просто обвести контур жеста. 
Самое главное чтобы пользователь, посмотрев на жест, понял как его показать.

**Comment by PoroshinGA** [comment]
Можно взять фотки жестов на белом фоне, с помощью AI удалить фон и конвертировать с помощью AI в svg формат
