### ISSUE TITLE
[Backend] Реализовать Room  базу данных в модуле :data

### ISSUE THREAD

**Issue by PoroshinGA** [PavelStalone/GestureTranslator#37]
Создать базу данных пользователей, которая будет содержать следующие  поля

- Почта 
- Пароль
- Состояние подписки

**Comment by PavelStalone** [comment]
Не забудь сделать все через Repository.
Интерфейс Repository должен находиться в модуле :domain, а сама реализация в :data.
Также сделай UseCase для взаимодействия с репозиторием.
