### ISSUE TITLE
[Design] Разработать новый UI на основе нового UX

### ISSUE THREAD

**Issue by PoroshinGA** [PavelStalone/GestureTranslator#39]
Разработать новый UI с учетом ухода от бургера к странице с меню

**Comment by PoroshinGA** [comment]
Мне кажется остановка перевода посредством поднимания шторки - это не особо удобная фича( Получится ли добавить к этому UI/UX кнопку для этого?

**Comment by kond1ter** [comment]
Сегодня постараюсь сделать пару вариантов
